### ISSUE TITLE
OpenCover throwing errors during a build process

### ISSUE THREAD

**Issue by asmagin** [asmagin/Cake.Sitecore#12]
When running task `Unit Tests :: Run Server Tests` following error appears in logs.
```
Sources directory not set, will try to guess. This might not work properly when merging results from multiple test assemblies.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: str
   at System.Text.RegularExpressions.Regex.Escape(String str)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreateRootElement(XDocument openCoverReport, String sourcesDirectory, Boolean includeGettersSetters)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.ConvertToCobertura(XDocument openCoverReport, String sourcesDirectory, Boolean includeGettersSetters)
   at Palmmedia.OpenCoverToCoberturaConverter.Program.Main(String[] args)
```

**Comment by asmagin** [comment]
Fixed by https://github.com/danielpalme/OpenCoverToCoberturaConverter/issues/21
